<?php
$data = array (
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '男装专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '男装专区',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '裤装',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '裤装',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '鞋',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '鞋',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '牛仔裤',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '上装',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '上装',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '针织衫',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'T恤衫',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '20',
    'name' => 'T恤衫',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '马甲',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '马甲',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '21',
    'name' => '衬衫',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '外套',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '鞋包配饰',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '鞋包配饰',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '时尚女装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '时尚女装',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '裤袜',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '裤袜',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '半身裙',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '半身裙',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '配饰',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '包',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '13',
    'name' => '包',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '裤装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '8',
    'name' => '裤装',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '上装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '7',
    'level' => 1,
    'id' => '2',
    'name' => '上装',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '夹克/大衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '4',
    'name' => '夹克/大衣',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '开襟衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '5',
    'name' => '开襟衫',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '★匡威',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '12',
    'name' => '★匡威',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '裙装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '裙装',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '鞋',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '11',
    'name' => '鞋',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '6',
    'name' => '连衣裙',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '衬衫/罩衫',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '3',
    'name' => '衬衫/罩衫',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '优雅OL',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '优雅OL',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '包包系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '30',
    'name' => '包包系列',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '辣妈包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '辣妈包',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '商务男包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '商务男包',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '首饰',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '首饰',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '旅行箱',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '旅行箱',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '可爱童装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '18',
    'name' => '可爱童装',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '电子数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '34',
    'name' => '电子数码',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '欧美风尚',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '欧美风尚',
  ),
);
?>